export const paths = {
  login: "/auth/login",
  signup: "/auth/signup",
  forgetPassword: "/auth/forget-password",
  home: "/",
  about: "/about",
  contact: "/contact",
  menu: "/menu",
  itemDetail: "/menu/item-detail/",
  itemDetailParam: "/menu/item-detail/:Itemid",
  profile: "/profile",
  orders: "/orders",
  cart: "/cart",
  checkout: "/checkout",
  payment: "/payment",
  notFound: "/*",
};
