export const SIGNUP_USER_LOADING = "SIGNUP_USER_LOADING";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_ERROR = "SIGNUP_USER_ERROR";

export const LOGIN_USER_LOADING = "LOGIN_USER_LOADING";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";

export const PROFILE_GETDATA_LOADING = "PROFILE_GETDATA_LOADING";
export const PROFILE_GETDATA_SUCCESS = "PROFILE_GETDATA_SUCCESS";
export const PROFILE_GETDATA_ERROR = "PROFILE_GETDATA_ERROR";

export const MENU_GETDATA_LOADING = "MENU_GETDATA_LOADING";
export const MENU_GETDATA_SUCCESS = "MENU_GETDATA_SUCCESS";
export const MENU_GETDATA_ERROR = "MENU_GETDATA_ERROR";

export const SINGLE_ITEM_GET_LOADING = "SINGLE_ITEM_GET_LOADING";
export const SINGLE_ITEM_GET_SUCCESS = "SINGLE_ITEM_GET_SUCCESS";
export const SINGLE_ITEM_GET_ERROR = "SINGLE_ITEM_GET_ERROR";

export const ABOUT_POST_LOADING = "ABOUT_POST_LOADING";
export const ABOUT_POST_SUCCESS = "ABOUT_POST_SUCCESS";
export const ABOUT_POST_ERROR = "ABOUT_POST_ERROR";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
